version: '2'
services:
  server:
    build:
      context: ./book_server
      dockerfile: dev.Dockerfile
    command: /app/server.R
    volumes:
     - ./book_server:/app
    restart: always
    ports:
     - "8000:8000"
